FROM pytorch/pytorch:2.9.1-cuda12.1-cudnn9-runtime 

RUN pip3 install --upgrade pip 

RUN pip3 install numpy scipy  

COPY workspace/requiremets.txt requiremets.txt
RUN pip3 install -r requiremets.txt 

RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

WORKDIR /home 

CMD ["nvidia-smi"]

