#Configurazione 4:	"Top Performance"
# config.yaml
# hyperparameters for MusicNet
# balance quality and training (1-3h)

dataset:
  csv_file: "data/solo_piano.csv"
  data_dir: "data/raw"
  chunk_duration: 7.0
  sample_rate: 22050

model :
  input_features: 84
  hidden_size: 512
  lstm_layers: 3
  dropout: 0.4

training:
  batch_size: 12
  epochs: 100
  learning_rate: 0.0003
  scheduler_patience: 7
  scheduler_factor: 0.5
  checkpoint_path: "top_performance_best_model.pt"
  pos_weight : 12

evaluation:
  threshold: 0.25
